services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app:z
      - root:/root/.local:z
      - target:/app/target
      - node_modules:/app/node_modules
      - images:/images
    ports:
      - 3000:3000
    environment:
      - IMAGE_DIR=/images
      - PGUSER=postgres
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/carte
      - MARTIN_URL=http://localhost:3001
      - KEYCLOAK_EXTERN_URL=http://localhost:8080/realms/master
      - KEYCLOAK_LOCAL_URL=http://keycloak:8080/realms/master
      - ENV=dev
    depends_on:
      - db
  martin:
    image: ghcr.io/maplibre/martin:v0.11.2
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/carte
    ports:
      - 3001:3000
    depends_on:
      - db
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: carte
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data:z
    ports:
      - 5432:5432
  keycloak:
    image: bitnami/keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: db
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_USER: postgres
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_PASSWORD: postgres
    ports:
      - 8080:8080
volumes:
  root:
  db:
  target:
  node_modules:
  images:
    
