services:
  veloinfo:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app:z
      - root:/root/.local:z
      - target:/app/target
      - node_modules:/app/node_modules
      - images:/images
    ports:
      - 3000:3000
    environment:
      - IMAGE_DIR=/images
      - PGUSER=postgres
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/carte
      - MARTIN_URL=http://localhost:3001
      - KEYCLOAK_BROWSER_URL=http://keycloak.veloinfo.ca/realms/master
      - KEYCLOAK_SERVER_URL=http://keycloak.veloinfo.ca/realms/master
      - VELOINFO_URL=http://localhost:3000
      - ENV=dev
    depends_on:
      - db
  martin:
    image: ghcr.io/maplibre/martin:v0.11.2
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/carte
    ports:
      - 3001:3000
    depends_on:
      - db
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: carte
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data:z
    ports:
      - 5432:5432
volumes:
  root:
  db:
  target:
  node_modules:
  images:
    
