services:
  dev:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app:z
      - root:/root/.local:z
      - target:/app/target
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    environment:
      - PGUSER=postgres
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/carte
  martin:
    image: ghcr.io/maplibre/martin:v0.11.2
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/carte
    ports:
      - 3001:3000
    depends_on:
      - db
  db:
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: carte
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data:z
    ports:
      - 5432:5432
volumes:
  root:
  db:
  target:
  node_modules: