services:
  dev:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app:z
      - root:/root:z
    ports:
      - 3000:3000
    environment:
      - PGPASSWORD=postgres 
  martin:
    image: ghcr.io/maplibre/martin:v0.11.2
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/carte
    ports:
      - 3001:3000
    depends_on:
      - db
  # nginx:
  #   image: nginx:alpine
  #   restart: unless-stopped
  #   ports:
  #     - "3001:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - martin  
  db:
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carte
    volumes:
      - db:/var/lib/postgresql/data:z
    ports:
      - 5432:5432
volumes:
  root:
  db: